import { Client, InventoryItem, OrderStatus, Quote, ServiceOrder, Transaction, ExecutedService } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Empresa Alpha Uniformes',
    documentType: 'CNPJ',
    documentNumber: '12.345.678/0001-90',
    contactPerson: 'Carlos Mendes',
    category: 'Empresa',
    email: 'contato@alphauniformes.com.br',
    phone: '(11) 98765-4321',
    cityState: 'São Paulo, SP - Vila Mariana',
    hasEmbroideryMachine: true,
    embroideryMachines: [
      { brand: 'Tajima', model: 'TME-DC', hoops: '15x15cm', fileFormat: 'DST' }
    ],
    matrixDeliveryPreferences: ['Email', 'Whatsapp'],
    activeOrdersCount: 1,
    avatarInitials: 'EA',
    avatarBgColor: 'bg-indigo-100 text-indigo-800'
  },
  {
    id: 'cli-2',
    name: 'Maria Eventos Corporativos',
    documentType: 'CPF',
    documentNumber: '123.456.789-00',
    contactPerson: 'Maria Silva',
    category: 'Particular',
    email: 'maria@eventos.com.br',
    phone: '(11) 99999-8888',
    cityState: 'São Paulo, SP - Moema',
    instagram: '@mariaeventos',
    hasEmbroideryMachine: true,
    embroideryMachines: [
      { brand: 'Brother', model: 'BP2100', hoops: '13x18cm', fileFormat: 'PES' }
    ],
    matrixDeliveryPreferences: ['Whatsapp', 'Telegram'],
    activeOrdersCount: 2,
    avatarInitials: 'ME',
    avatarBgColor: 'bg-red-100 text-red-800'
  },
  {
    id: 'cli-3',
    name: 'Colégio São Judas',
    documentType: 'CNPJ',
    documentNumber: '98.765.432/0001-10',
    contactPerson: 'Diretoria',
    category: 'Escola',
    email: 'secretaria@saojudas.edu.br',
    phone: '(11) 3333-4444',
    cityState: 'São Paulo, SP - Tatuapé',
    hasEmbroideryMachine: true,
    embroideryMachines: [
      { brand: 'Janome', model: 'MC500E', hoops: '20x20cm', fileFormat: 'JEF' }
    ],
    matrixDeliveryPreferences: ['Email'],
    activeOrdersCount: 0,
    avatarInitials: 'CS',
    avatarBgColor: 'bg-slate-200 text-slate-800'
  }
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: '#105',
    clientId: 'cli-2',
    clientName: 'Maria Eventos Corporativos',
    date: '12/10/2023',
    productType: 'virtual',
    embroiderySize: '10x10cm',
    hoopSize: '13x18cm',
    fabricType: 'Algodão',
    fabricColor: 'Branco',
    description: 'Bordado frontal camisa polo, 15 cores, logo corporativo',
    estimatedValue: 150.00,
    status: 'Aprovado',
    stitchCount: 14500,
    matrixFileName: 'logo_maria_eventos.dst',
    matrixUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: '#104',
    clientId: 'cli-1',
    clientName: 'Empresa Alpha Uniformes',
    date: '10/10/2023',
    productType: 'fisico',
    embroiderySize: '8x8cm',
    hoopSize: '10x10cm',
    fabricType: 'Piquet',
    fabricColor: 'Azul Marinho',
    description: 'Monograma peitoral para dólmãs de chefs',
    estimatedValue: 85.00,
    status: 'Aprovado',
    stitchCount: 8200,
    matrixFileName: 'monograma_alpha.pes',
    matrixUrl: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=600&auto=format&fit=crop&q=80'
  },
  {
    id: '#103',
    clientId: 'cli-3',
    clientName: 'Colégio São Judas',
    date: '08/10/2023',
    productType: 'virtual',
    embroiderySize: '15x15cm',
    hoopSize: '20x20cm',
    fabricType: 'Moletom',
    fabricColor: 'Cinza Mescla',
    description: 'Brazão escolar para jaquetas de formandos',
    estimatedValue: 320.00,
    status: 'Pendente',
    stitchCount: 26000,
    matrixFileName: 'brasao_saojudas.dst'
  }
];

export const INITIAL_ORDERS: ServiceOrder[] = [
  {
    id: 'OS #26001',
    clientId: 'cli-1',
    clientName: 'Acme Corp',
    quoteId: '#104',
    productType: 'fisico',
    status: 'Em Andamento',
    creationDate: '12/10/2026',
    deliveryDate: '20/10/2026',
    totalValue: 500.00,
    paidValue: 500.00,
    isSinglePayment: false,
    description: 'Bordados de logomarca em 25 camisas sociais corporativas.',
    imageUrl: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=600&auto=format&fit=crop&q=80',
    embroiderySize: '8x8cm',
    hoopSize: '10x10cm',
    fabricType: 'Piquet',
    fabricColor: 'Azul Marinho',
    stitchCount: 8200,
    matrixFileName: 'monograma_alpha.pes',
    matrixDeliveryPreferences: ['Email', 'Whatsapp'],
    machineFileFormat: 'PES',
    notes: 'Linha de alta resistência, acabamento em cetim azul e dourado.',
    steps: [
      { title: 'Enviada para aprovação', date: '12/10/2026', completed: true, type: 'approval' },
      { title: 'Pagamento 1', date: '13/10/2026', completed: true, type: 'payment1', amount: 250 },
      { title: 'Pagamento 2', date: '15/10/2026', completed: true, type: 'payment2', amount: 250 },
      { title: 'Envio definitivo', date: '20/10/2026', completed: false, type: 'shipping' }
    ]
  },
  {
    id: 'OS #26002',
    clientId: 'cli-2',
    clientName: 'Boutique Silva',
    quoteId: '#105',
    productType: 'virtual',
    status: 'Aguardando',
    creationDate: '14/10/2026',
    deliveryDate: '25/10/2026',
    totalValue: 280.00,
    paidValue: 0,
    isSinglePayment: false,
    description: 'Bordado de detalhes florais em vestidos de festa.',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    embroiderySize: '10x10cm',
    hoopSize: '13x18cm',
    fabricType: 'Algodão',
    fabricColor: 'Branco',
    stitchCount: 14500,
    matrixFileName: 'logo_maria_eventos.dst',
    matrixDeliveryPreferences: ['Whatsapp', 'Telegram'],
    machineFileFormat: 'DST',
    notes: 'Utilizar entretela hidrossolúvel para não marcar a renda do vestido.',
    steps: [
      { title: 'Enviada para aprovação', date: '14/10/2026', completed: true, type: 'approval' },
      { title: 'Pagamento 1', date: 'Pendente', completed: false, type: 'payment1' },
      { title: 'Pagamento 2', date: 'Pendente', completed: false, type: 'payment2' },
      { title: 'Envio definitivo', date: 'Pendente', completed: false, type: 'shipping' }
    ]
  },
  {
    id: 'OS #26003',
    clientId: 'cli-3',
    clientName: 'TechWear Brasil',
    status: 'Concluído',
    creationDate: '01/10/2026',
    deliveryDate: '12/10/2026',
    totalValue: 1200.00,
    paidValue: 1200.00,
    isSinglePayment: false,
    description: 'Jaquetas refletivas com brasão bordado em alta densidade.',
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&auto=format&fit=crop&q=80',
    embroiderySize: '15x15cm',
    hoopSize: '20x20cm',
    fabricType: 'Nylon Impermeável',
    fabricColor: 'Preto / Refletivo',
    stitchCount: 26000,
    matrixFileName: 'brasao_techwear.dst',
    matrixDeliveryPreferences: ['Email'],
    machineFileFormat: 'JEF',
    notes: 'Entregue com sucesso por transportadora.',
    steps: [
      { title: 'Enviada para aprovação', date: '01/10/2026', completed: true, type: 'approval' },
      { title: 'Pagamento 1', date: '05/10/2026', completed: true, type: 'payment1', amount: 600 },
      { title: 'Pagamento 2', date: '10/10/2026', completed: true, type: 'payment2', amount: 600 },
      { title: 'Envio definitivo', date: '12/10/2026', completed: true, type: 'shipping' }
    ]
  }
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'mat-1',
    code: 'L-114',
    name: 'Linha de Bordado Azul Royal 114 (Polyester 120D/2)',
    category: 'Linha de Bordado',
    imageUrl: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=600&auto=format&fit=crop&q=80',
    tag: 'Alta Rotação',
    stockQuantity: 42,
    unit: 'retós',
    minStockLevel: 10,
    colorHex: '#120a8f',
    colorName: 'Azul Royal',
    pricePerUnit: 18.50,
    hasFractioning: true,
    fractionSize: 500,
    fractionUnit: 'm',
    pricePerFractionUnit: 0.037
  },
  {
    id: 'mat-2',
    code: 'L-GOLD',
    name: 'Linha Metálica Dourada - Madeira Art. 1234 / 500m',
    category: 'Linha de Bordado',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    tag: 'Estoque Baixo',
    stockQuantity: 3,
    unit: 'retós',
    minStockLevel: 5,
    colorHex: '#d4af37',
    colorName: 'Ouro Reluzente',
    pricePerUnit: 34.00,
    hasFractioning: true,
    fractionSize: 500,
    fractionUnit: 'm',
    pricePerFractionUnit: 0.068
  },
  {
    id: 'mat-3',
    code: 'ENT-80',
    name: 'Entretela Rasga Para Lado Estabonada 80g Branco (50m)',
    category: 'Entretela',
    imageUrl: 'https://images.unsplash.com/photo-1528458876861-544fd1761a91?w=600&auto=format&fit=crop&q=80',
    tag: 'Normal',
    stockQuantity: 15,
    unit: 'rolo',
    minStockLevel: 8,
    colorHex: '#ffffff',
    colorName: 'Branco',
    pricePerUnit: 60.00,
    hasFractioning: true,
    fractionSize: 50,
    fractionUnit: 'm',
    pricePerFractionUnit: 1.20
  },
  {
    id: 'mat-4',
    code: 'AG-DBK5',
    name: 'Agulhas Organ Needles DBxK5 Nº 75/11 (Caixa c/ 100)',
    category: 'Agulha',
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    tag: 'Alta Rotação',
    stockQuantity: 8,
    unit: 'caixas',
    minStockLevel: 2,
    pricePerUnit: 65.00,
    hasFractioning: true,
    fractionSize: 100,
    fractionUnit: 'unidades',
    pricePerFractionUnit: 0.65
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    date: '12/10/2026',
    description: 'Pagamento OS #26001',
    type: 'entrada',
    amount: 150.00,
    balanceAfter: 150.00,
    category: 'Pagamento OS'
  },
  {
    id: 'tx-2',
    date: '13/10/2026',
    description: 'Compra de Linhas',
    type: 'saida',
    amount: 50.00,
    balanceAfter: 100.00,
    category: 'Compra de Linhas'
  },
  {
    id: 'tx-3',
    date: '14/10/2026',
    description: 'Sinal OS #26002',
    type: 'entrada',
    amount: 500.00,
    balanceAfter: 600.00,
    category: 'Sinal OS'
  },
  {
    id: 'tx-4',
    date: '15/10/2026',
    description: 'Manutenção Máquina 2',
    type: 'saida',
    amount: 350.00,
    balanceAfter: 250.00,
    isUrgent: true,
    category: 'Manutenção'
  }
];

export const INITIAL_SERVICES: ExecutedService[] = [
  {
    id: 'srv-1',
    code: 'SRV-001',
    name: 'Bordado Peitoral de Logomarca (Até 10x10cm)',
    category: 'Bordado Computadorizado',
    subcategory: 'Uniformes & Trabalho',
    description: 'Bordado direto em camisas polo, dólmãs ou jaquetas. Inclui entretela rasgável e acabamento de fios.',
    defaultPrice: 25.00,
    unit: 'peça',
    productType: 'fisico',
    estimatedStitchCount: 12000,
    suggestedEmbroiderySize: '10x10cm',
    suggestedHoopSize: '13x18cm',
    estimatedTimeMinutes: 20,
    imageUrl: 'https://images.unsplash.com/photo-1605518216938-7c31b7b14ad0?w=600&auto=format&fit=crop&q=80',
    tags: ['Mais Vendido', 'Produto Físico', 'Alta Rotação'],
    timesExecuted: 48,
    lastUsedDate: '30/07/2026'
  },
  {
    id: 'srv-2',
    code: 'SRV-002',
    name: 'Programação de Matriz Computadorizada (Digitalização)',
    category: 'Programação de Matriz',
    subcategory: 'Matrizes de Bastidor',
    description: 'Criação e conversão de vetor/imagem para arquivos de máquina (DST, PES, JEF, EXP, HUS). Teste e simulação em software.',
    defaultPrice: 85.00,
    unit: 'matriz',
    productType: 'virtual',
    estimatedStitchCount: 15000,
    suggestedEmbroiderySize: '12x12cm',
    suggestedHoopSize: '13x18cm',
    estimatedTimeMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    tags: ['Matriz Virtual', 'Digitalização', 'Alta Margem'],
    timesExecuted: 32,
    lastUsedDate: '28/07/2026'
  },
  {
    id: 'srv-3',
    code: 'SRV-003',
    name: 'Bordado de Monograma / Nome em Jaleco / Uniforme',
    category: 'Personalização & Monograma',
    subcategory: 'Nomes & Iniciais',
    description: 'Bordado de nome profissional + profissão/especialidade no bolso do jaleco, avental ou dólmã.',
    defaultPrice: 35.00,
    unit: 'unidade',
    productType: 'fisico',
    estimatedStitchCount: 6500,
    suggestedEmbroiderySize: '8x4cm',
    suggestedHoopSize: '10x10cm',
    estimatedTimeMinutes: 12,
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    tags: ['Área da Saúde', 'Personalização', 'Rápido'],
    timesExecuted: 65,
    lastUsedDate: '01/08/2026'
  },
  {
    id: 'srv-4',
    code: 'SRV-004',
    name: 'Aplicação de Patch / Escudo Termocolante',
    category: 'Aplicação & Patch',
    subcategory: 'Patchs & Emblemas',
    description: 'Confecção de brasão bordado com fundo reforçado e aplicação com prensa térmica ou costura de borda.',
    defaultPrice: 45.00,
    unit: 'unidade',
    productType: 'fisico',
    estimatedStitchCount: 22000,
    suggestedEmbroiderySize: '12x12cm',
    suggestedHoopSize: '15x15cm',
    estimatedTimeMinutes: 30,
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&auto=format&fit=crop&q=80',
    tags: ['Patch', 'Escola', 'Moto Clube'],
    timesExecuted: 19,
    lastUsedDate: '22/07/2026'
  },
  {
    id: 'srv-5',
    code: 'SRV-005',
    name: 'Bordado Costas Grande (Jaqueta / Moletom)',
    category: 'Bordado Computadorizado',
    subcategory: 'Uniformes & Trabalho',
    description: 'Bordado em grande escala para costas de jaquetas, moletons e uniformes de equipes.',
    defaultPrice: 120.00,
    unit: 'peça',
    productType: 'fisico',
    estimatedStitchCount: 45000,
    suggestedEmbroiderySize: '25x25cm',
    suggestedHoopSize: '30x30cm',
    estimatedTimeMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    tags: ['Grande Formato', 'Alta Densidade'],
    timesExecuted: 14,
    lastUsedDate: '15/07/2026'
  }
];
